
`ifndef VIVE_CONSTANTS
`define VIVE_CONSTANTS

// DURATION

`define PULSE_DURATION_PULSE 40

`define PULSE_DURATION_X0_LOW 60
`define PULSE_DURATION_X0_HIGH 72

`define PULSE_DURATION_Y0_LOW 71
`define PULSE_DURATION_Y0_HIGH 82

`define PULSE_DURATION_X1_LOW 81
`define PULSE_DURATION_X1_HIGH 92

`define PULSE_DURATION_Y1_LOW 91
`define PULSE_DURATION_Y1_HIGH 102

`define PULSE_DURATION_X0_SKIP_LOW 101
`define PULSE_DURATION_X0_SKIP_HIGH 114

`define PULSE_DURATION_Y0_SKIP_LOW 113
`define PULSE_DURATION_Y0_SKIP_HIGH 124

`define PULSE_DURATION_X1_SKIP_LOW 123
`define PULSE_DURATION_X1_SKIP_HIGH 135

`define PULSE_DURATION_Y1_SKIP_LOW 134
`define PULSE_DURATION_Y1_SKIP_HIGH 148

// DURATION

// PULSE TYPE

`define PULSE_TYPE_INTERVAL 0
`define PULSE_TYPE_X0       1
`define PULSE_TYPE_Y0       2
`define PULSE_TYPE_X1       3
`define PULSE_TYPE_Y1       4
`define PULSE_TYPE_X0_SKIP  5
`define PULSE_TYPE_Y0_SKIP  6
`define PULSE_TYPE_X1_SKIP  7
`define PULSE_TYPE_Y1_SKIP  8
`define PULSE_TYPE_LASER    9
`define PULSE_TYPE_SIZE     10
`define PULSE_TYPE_SIZE_OF  4

// PULSE TYPE

`endif

